module.exports = {
    ENTITY_TYPE_ITEM: 'ENTITY_TYPE_ITEM',
    ENTITY_TYPE_CREATURE: 'ENTITY_TYPE_CREATURE',

    DAMAGE_TYPE_LETHAL: 0,
    DAMAGE_TYPE_STUNNING: 1,
    DAMAGE_TYPE_PENETRATING: 2, // Can be reduced by armor
    DAMAGE_TYPE_BLUNT: 4, // Can be reduce by TGH and armor
    DAMAGE_TYPE_SPECIAL: 8,

    ITEM_TYPE_ARMOR: 'ITEM_TYPE_ARMOR',

    WEAPON_CATEGORY_BLUNT: 'WEAPON_CATEGORY_BLUNT', // club, mace, hammer, morningstar
    WEAPON_CATEGORY_BLADE: 'WEAPON_CATEGORY_BLADE', // sword, rapier, katana, wakizashi,
    WEAPON_CATEGORY_AXE: 'WEAPON_CATEGORY_AXE', // all types of axes
    WEAPON_CATEGORY_KNIFE: 'WEAPON_CATEGORY_KNIFE', // small blade, dirk, dagger, tanto
    WEAPON_CATEGORY_POLEARM: 'WEAPON_CATEGORY_POLEARM', // 2-hands ! halberd, staff, glaive, spear, lance, pike
    WEAPON_CATEGORY_FLEXIBLE: 'WEAPON_CATEGORY_FLEXIBLE', // chain, flail, nunchaku, whip, three-section-staff
    WEAPON_CATEGORY_SMALL_ARM: 'WEAPON_CATEGORY_SMALL_ARM', // pistol, rifle

    COMBAT_WEAPON_REACH_BALANCED: 'COMBAT_WEAPON_REACH_BALANCED',
    COMBAT_WEAPON_REACH_ATTACKER_ADVANTAGED: 'COMBAT_WEAPON_REACH_ATTACKER_ADVANTAGED',
    COMBAT_WEAPON_REACH_DEFENDER_ADVANTAGED: 'COMBAT_WEAPON_REACH_DEFENDER_ADVANTAGED',

    MATERIAL_WOOD: 'MATERIAL_WOOD',
    MATERIAL_STEEL: 'MATERIAL_STEEL',
    MATERIAL_ALUMINUM: 'MATERIAL_ALUMINUM',
    MATERIAL_SILVER: 'MATERIAL_ALUMINUM',

    CONDITION_STUNNED: 'CONDITION_STUNNED',

    EQUIPMENT_SLOT_HEAD: 'head', // helms, caps
    EQUIPMENT_SLOT_NECK: 'neck', // necklaces, amulets
    EQUIPMENT_SLOT_CHEST: 'chest', // armors
    EQUIPMENT_SLOT_ARMS: 'arms', // bracers, gauntlets
    EQUIPMENT_SLOT_BACK: 'back', // capes, backpacks
    EQUIPMENT_SLOT_WAIST: 'waist', // belts
    EQUIPMENT_SLOT_FEET: 'feet', // boots
    EQUIPMENT_SLOT_LEFTFINGER: 'leftFinger', // rings
    EQUIPMENT_SLOT_RIGHTFINGER: 'rightFinger', // rings
    EQUIPMENT_SLOT_MELEEWEAPON: 'meleeWeapon',
    EQUIPMENT_SLOT_RANGEDWEAPON: 'rangedWeapon',
    EQUIPMENT_SLOT_SHIELD: 'shield',
    EQUIPMENT_SLOT_AMMO: 'ammo',

    SKILL_MELEE_WEAPON: 'SKILL_MELEE_WEAPON', // épée, masse, dague
    SKILL_MELEE_WEAPON_BLADE: 'SKILL_MELEE_WEAPON_BLADE', // épée, dague
    SKILL_MELEE_WEAPON_BLUNT: 'SKILL_MELEE_WEAPON_BLUNT', // masse, marteau
    SKILL_MELEE_WEAPON_AXE: 'SKILL_MELEE_WEAPON_AXE', // hachette, hache d'arme
    SKILL_MELEE_WEAPON_POLEARM: 'SKILL_MELEE_WEAPON_POLEARM', // baton, halebarde...


    SKILL_MISSILE_WEAPON: 'SKILL_MISSILE_WEAPON', // arbalète, arc, fronde
    SKILL_SMALL_ARM: 'SKILL_SMALL_ARM', // Pistolets, fusil d'assaut

}
